database:
  type: sqlite
  path: data/database.sqlite
server:
  port: 8443
  cert: example/server.crt
  key: example/server.key
  staticDir: ui/build
  docsDir: gen/openapiv2
  metrics:
    port: 9101
    measureLatency: true
tenant:
  emailDomain: redhat.com
  password: SecretPassW0rd!
  oidcConfigFile: example/oidc.yaml
