database:
  type: sqlite
  path: "data/database.sqlite"
  # type: postgres
  # host: localhost
  # port: 5432
  # user: postgres
  # password: mysecretpassword
  # name: postgres
server:
  port: 8443
  cert: example/server.crt
  key: example/server.key
tenant:
  emailDomain: redhat.com
