apiVersion: v1
# TODO: this must be a secret
kind: ConfigMap
metadata:
metadata:
  name: {{ include "release-registry.fullname" . }}-configuration
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "release-registry.labels" . | nindent 4 }}
data:
  config.yaml: |
    database:
      type: postgres
    server:
      port: {{ .Values.service.port }}
      cert: /config/server.crt
      key: /config/server.key
      staticDir: ui/build
    tenant:
      emailDomain: {{ .Values.server.emailDomain }}
      password: {{ .Values.server.adminPassword }}
      oidcConfigFile: /config/oidc.yaml

  server.crt: {{- .Values.server.cert | toYaml | indent 2 }}
  server.key: {{- .Values.server.key | toYaml | indent 2 }}

  oidc.yaml: |
{{ toYaml .Values.oidc | indent 4 }}
