---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "release-registry.fullname" . }}-configuration
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "release-registry.labels" . | nindent 4 }}
data:
  config.yaml: {{ include "release-registry.configuration" . | b64enc }}
  oidc.yaml: {{ .Values.oidc | toYaml | b64enc }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ include "release-registry.fullname" . }}-certs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "release-registry.labels" . | nindent 4 }}
data:
  tls.crt: {{ .Values.server.cert | b64enc }}
  tls.key: {{ .Values.server.key | b64enc }}
