apiVersion: v1
data:
  config.yaml: |
    database:
      type: sqlite
      path: "data/database.sqlite"
    server:
      port: 8443
kind: ConfigMap
metadata:
metadata:
  name: {{ include "release-registry.fullname" . }}-configuration
  labels:
    {{- include "release-registry.labels" . | nindent 4 }}
