apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "release-registry.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "release-registry.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "release-registry.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configuration.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "release-registry.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ include "release-registry.fullname" . }}-pull-secret
      serviceAccountName: {{ include "release-registry.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: https
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz/liveness
              port: https
              scheme: HTTPS
          readinessProbe:
            httpGet:
              path: /healthz/readiness
              port: https
              scheme: HTTPS
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: RELREG_DATABASE_HOST
            valueFrom:
              secretKeyRef:
                name: {{ include "release-registry.fullname" . }}-pguser-{{ include "release-registry.fullname" . }}
                key: host
          - name: RELREG_DATABASE_PORT
            valueFrom:
              secretKeyRef:
                name: {{ include "release-registry.fullname" . }}-pguser-{{ include "release-registry.fullname" . }}
                key: port
          - name: RELREG_DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: {{ include "release-registry.fullname" . }}-pguser-{{ include "release-registry.fullname" . }}
                key: dbname
          - name: RELREG_DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: {{ include "release-registry.fullname" . }}-pguser-{{ include "release-registry.fullname" . }}
                key: user
          - name: RELREG_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "release-registry.fullname" . }}-pguser-{{ include "release-registry.fullname" . }}
                key: password
          volumeMounts:
          - name: config
            mountPath: "/config"
            readOnly: true
          - name: certs
            mountPath: "/certs"
            readOnly: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: config
        secret:
          secretName: {{ include "release-registry.fullname" . }}-configuration
      - name: certs
        secret:
          secretName: {{ include "release-registry.fullname" . }}-certs
