{{ if ne .Values.deployment "local" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "release-registry.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "release-registry.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.reservedAddressName }}
    networking.gke.io/managed-certificates: {{ include "release-registry.fullname" . }}-certificate
    networking.gke.io/v1beta1.FrontendConfig: {{ include "release-registry.fullname" . }}
spec:
  defaultBackend:
    service:
      name: {{ include "release-registry.fullname" . }}
      port:
        number: {{ .Values.service.port }}
{{ end }}
