---
apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.pullSecret | b64enc }}
kind: Secret
metadata:
  name: {{ include "release-registry.fullname" . }}-pull-secret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
