---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "release-registry.fullname" . }}-pull-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "release-registry.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "release-registry.imagePullSecret" . }}
