apiVersion: v1
kind: Service
metadata:
  name: {{ include "release-registry.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "release-registry.labels" . | nindent 4 }}
  annotations:
    cloud.google.com/app-protocols: '{"https":"HTTP2"}'
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: https
  selector:
    {{- include "release-registry.selectorLabels" . | nindent 4 }}
