# Controls whether ingress and certificate are deployed.
# Expected values production|development|local
deployment: ''

# Name of the global IP created on GKE for the ingress
reservedAddressName: ''

# Ingress contains the registered domains for the deployment.
# Ensure at your name server that they point to the global IP.
ingress:
  hosts: []

# ImageRegistry is used to construct and encode the image pull secret.
imageRegistry:
  # Name of the image registry, e.g. quay.io
  name: ''
  # Username
  username: ''
  # Password (plaintext)
  password: ''

server:
  # Use this password for protected endpoints that only admin users can access.
  adminPassword: ''

  # Private key of RSA keypair for the secured communication of the gRPC gateway.
  key: ''
  # Public key of RSA keypair for the secured communication of the gRPC gateway.
  cert: ''

# Configuration for the user authentication.
oidc:
  # OIDC issuer URL, commonly shared as issuerURL.
  issuer: ''
  # To identify the client/application on the OIDC endpoint.
  clientID: ''
  # To authenticate the client/application on the OIDC endpoint.
  clientSecret: ''
  # Added to the service account token as server signature.
  sessionSecret: ''
  # For redirects after login.
  endpoint: ''
  # Lifetime of the service account tokens, must be in Go duration format, e.g. 7h3m45s.
  tokenLifetime: ''
  # Control for access to service.
  allowedEmailSuffix: ''
