name: Build
on:
  push:
    branches:
      - main
      - tm/repo-setup
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.5

      - name: Setup env
        run: |
          GOPATH="$GITHUB_WORKSPACE/go"
          echo GOPATH="${GOPATH}" >> "$GITHUB_ENV"
          PATH="${PATH}:${GOPATH}/bin"
          echo PATH="${PATH}" >> "$GITHUB_ENV"

      - name: Build CLI
        run: |
          set -euo pipefail
          go mod download && go mod verify
          make proto-install && make proto-generate
          make cli-binary

  build-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          path: go/src/github.com/stackrox/release-registry

      - name: Build server image
        run: |
          make server-image
