name: Build and Push

on:
  push:
    branches:
      - main
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Run linters
        run: |
          make install-linters lint

  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-type: [ unit, integration, e2e ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Run ${{ matrix.test-type }} tests
        env:
          RELREG_TEST_TOKEN: ${{ secrets.RELREG_TEST_TOKEN }}
        run: |
          make tests-${{ matrix.test-type }}

  build-and-push:
    needs: [lint, run-tests]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          cache: true

      - name: Build server image
        run: |
          make server-image

      - name: Login to quay.io/rhacs-eng
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_RHACS_ENG_RW_USERNAME }}
          password: ${{ secrets.QUAY_RHACS_ENG_RW_PASSWORD }}

      - name: Push server image
        run: |
          make server-image-push
